### PR TITLE
Adding documentation structure for package

### PR DESCRIPTION
**Pull request by fontikar**
Addressing #59 

- Added package level documentation ?ausflora
- Added first rough draft vignette
- Added article place holders documentation for 'Caching in ausflora' and 'Name matching alogorithim'
- Updated DESCRIPTION in Suggests for packages needed for vignette (likely going to 'prerender' using RMD to save time in the future) 
- Added example data for illustration of functions

### CODE REVIEW

**Comment by dfalster** [comment]
Looks promising @fontikar but all tests failed, which is unexpcedt. Is there something up with GH?

**Comment by wcornwell** [comment]
just missing two commas in the description, I think. passes tests for me if you add those in

**Comment by fontikar** [comment]
> just missing two commas in the description, I think. passes tests for me if you add those in

Haha I just saw that too! :D Thanks will! All fixed

**Comment by fontikar** [comment]
Waiting on your review @wcornwell 🥇

**Comment by wcornwell** [comment]
how do i approve?

**Review by wcornwell — APPROVED** [review]
looks good to me! Vignette!

**Comment by wcornwell** [comment]
found it!  @fontikar can you squash and merge?

**Comment by dfalster** [comment]
Great work!

**Pull request merged**
