### PR TITLE
Add argument to turn fuzzy matching on/off in align_taxa

### LINKED ISSUE #12: Add option to "turn off" fuzzy matching in align_taxa?
Hello!

Would it be possible to add an argument in `align_taxa` to set fuzzy matching to `FALSE`?

Perhaps it is an unusual use case but I'm trying to run apcnames on a list of species that includes both Australian and a large number of international taxa. I'm only interested in the Australian taxa, but as the APC is the best source of info on what taxa are found in Australia I thought apcnames might be a good way to separate Aus from international taxa. Unfortunately though the fuzzy matching in `align_taxa` coerced a large number of genuses/species not found in Aus into adjacent Australian taxa.

I've figured out a workaround but thought perhaps it could be useful to have an argument to turn fuzzy matching in `align_taxa` on or off? Or could this be dealt with by changing the `max_distance` settings?

### PR DESCRIPTION
**Pull request by rubysaltbush**
Resolves #12 I hope, also fixed some typos

### CODE REVIEW

**Review by dfalster — COMMENTED** [review]
Looks good. Did you test it?

**Comment by rubysaltbush** [comment]
Took me a while to figure out how to load it into my project to test. Have done so now. Fixed unduplicated `=` in line 159, now seems to work in my project at least? Matches a few more names than my workaround (which was just left_joining to the APC's export table), probably because it's matching to APNI as well.

**Comment by rubysaltbush** [comment]
I've added the subclass column in the `update_taxonomy` output as this makes it easier to filter species outputs at a higher level e.g. to retain only Angiosperm species, as per issue #14 . I've installed my version and run it on my data set of ~4000 species, works as expected.

**Comment by rubysaltbush** [comment]
@fontikar @dfalster can this pull request be merged with the updated ausflora package? I'd like to use the latest version but still need to be able to turn fuzzy matching off (for global species lists) per issue #12  and filter taxa by subclass per #14

**Comment by fontikar** [comment]
Hey @rubysaltbush thanks for creating this PR! Its such a great idea! I'm happy to raise this with @dfalster will take it from there! Currently we are trying to allocate resources to ausflora so hopefully you will see more activity in the future! Sorry for the delays.

**Comment by wcornwell** [comment]
can we merge this in?

**Comment by wcornwell** [comment]
I've tested it and it works.

**Comment by dfalster** [comment]
Thanks @rubysaltbush , merged!

**Comment by rubysaltbush** [comment]
Great thanks @dfalster and @wcornwell !

**Pull request merged**
